### ISSUE TITLE
Not working on theano backed

### ISSUE THREAD

**Issue by prithi** [jakebian/quiver#1]
Do you have a plan to make a theano version of this tool?

**Comment by jakebian** [comment]
the only TF specific part is a sessions workaround that was needed to make the webserver thread work, Ican you describe what specific issue that you're having? Or is it only the tensorflow import is failing?

**Comment by prithi** [comment]
I am using Windows 10 and Theano for backend. Tensorflow is not installed in my system. 

Here is my sample code 


`from keras.models import model_from_json
from quiver_engine.server import launch


json_file = open('model\model.json', 'r')
model_json = json_file.read()
json_file.close()
model = model_from_json(model_json)
# load weights into new model
model.load_weights("weight\VGG19_v1_finetune.best.hdf5")
print("Loaded model from disk")

launch(model, input_folder='./img', port=7000)`

Error log:
`runfile('D:/Machine Learning/Models/Cal All/Model List/VGG19/VGG19_v1/visualize.py', wdir='D:/Machine Learning/Models/Cal All/Model List/VGG19/VGG19_v1')
Using Theano backend.
Using gpu device 0: GeForce GTX 1060 6GB (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5105)
Traceback (most recent call last):

  File "<ipython-input-1-e578861155e7>", line 1, in <module>
    runfile('D:/Machine Learning/Models/Cal All/Model List/VGG19/VGG19_v1/visualize.py', wdir='D:/Machine Learning/Models/Cal All/Model List/VGG19/VGG19_v1')

  File "D:\toolkits\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\toolkits\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Machine Learning/Models/Cal All/Model List/VGG19/VGG19_v1/visualize.py", line 2, in <module>
    from quiver_engine.server import launch

  File "D:\toolkits\Anaconda2\lib\site-packages\quiver_engine\server.py", line 21, in <module>
    import tensorflow as tf

ImportError: No module named tensorflow`

**Comment by jakebian** [comment]
Yeah as of now tensorflow is a dependency - but I think there's a way to do the import conditionally by checking what backend keras is configured to use, I'll look into this!

**Comment by prithi** [comment]
Please look into the problem. IMO, Quiver is the best visualization tool for Keras.

**Comment by isaacgerg** [comment]
I am several models built with Keras running Windows 7 and python 3.4 using the theano backend.  How can I help you with this issue?

**Comment by jakebian** [comment]
[Made the theano import optional](https://github.com/jakebian/quiver/commit/fa0ee734dc9af41d699eddbc07b6aa3d12f8ee46), and running with KERAS_BACKEND=theano works for me. Can you guys verify?

**Comment by isaacgerg** [comment]
the import for imagenet_utils is wrong in server.py,  should be keras.applications.imagenet_utils import decode_predictions.

**Comment by isaacgerg** [comment]
same with util, should be keras.utils.
What version of keras are you building to?

**Comment by jakebian** [comment]
@isaacgerg these are local files, I think you're having issues due to python3 import issues, which will be fixed by https://github.com/jakebian/quiver/pull/5

**Comment by isaacgerg** [comment]
deprocess_image is not in the current keras build as you call it.  Its in the examples directory in keras now.

**Comment by isaacgerg** [comment]
@jakebian   I see, these are local files as you said.  I was thinking you were using the files from keras.  I have to have my CWD set up and they should import.  Sorry!

**Comment by jakebian** [comment]
@isaacgerg utils is [this file](https://github.com/jakebian/quiver/blob/master/quiver_engine/util.py), you're just having python 3 import issues

**Comment by isaacgerg** [comment]
I am loading on port=5001.  Upon executing server.lauch the browser says 404 Not found.

**Comment by isaacgerg** [comment]
When using port 5000, it says Only one usage of each socket address is normally permitted.

**Comment by jakebian** [comment]
Are you building it locally with setup.py? If so as mentioned in the readme you need to compile the dashboard locally too.

side note: pip install should work now.

**Comment by isaacgerg** [comment]
sorry, im being such a noob.  Let me do the pip install and see if it works.... stand by

**Comment by isaacgerg** [comment]
Did "pip install quiver", was successful. Tried to run again, 404 not found.  Do i have to run npm?

**Comment by isaacgerg** [comment]
pip install quiver_engine is not working...


```
    writing quiver_engine.egg-info\PKG-INFO
    writing dependency_links to quiver_engine.egg-info\dependency_links.txt
    writing requirements to quiver_engine.egg-info\requires.txt
    writing top-level names to quiver_engine.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'quiver_engine.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'quiver_engine.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\idg101\AppData\Local\Temp\pip-build-8ffm_h7y\quiver-engine\setup.py", line 20, in <module>
        'pillow'
      File "c:\python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 47, in run
        self.build_package_data()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 103, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 59, in __getattr__
        self.data_files = files = self._get_data_files()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 86, in _get_data_files
        file[plen:] for file in self.find_data_files(package, src_dir)
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 94, in find_data_files
        + self.package_data.get(package, []))
    TypeError: can only concatenate list (not "str") to list

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\idg101\\AppData\\Local\\Temp\\pip-build-8ffm_h7y\\quiver-engin
e\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record C:\Users\idg101\AppData\Local\Temp\pip-2amt2zih-record\install-record.txt --single-version-externally-managed --compile" failed with error co
de 1 in C:\Users\idg101\AppData\Local\Temp\pip-build-8ffm_h7y\quiver-engine\
```

**Comment by prithi** [comment]
I run it successfully on windows 10 using Theano.  However, I think single_input_shape should be like this for theano as the input shape of theano is different than tensorflow. 

`single_input_shape = model.get_input_shape_at(0)[2:4]`

**Comment by isaacgerg** [comment]
@prithi How did you get past the npm stuff?  It bombs on my machine.

**Comment by prithi** [comment]
I just follow this steps @isaacgerg 

1. cd quiverboard
2. npm install
3. npm run deploy:prod

**Comment by isaacgerg** [comment]
Where do you get npm? Can you provide some instructions?

Upon googling, I found some package where i had to put the directory with
npm in quiverboard.

**Comment by prithi** [comment]
Just download [nodejs](https://nodejs.org/en/download/) and execute the commands

**Comment by isaacgerg** [comment]
@prithi Thank you, I got npm working (i think).

Did a fresh pull. 

On windows, I do a set QUIVER__URL=localhost:5001 instead of export.

Still getting 404 not found when I run quiver_engine.server.launch(model, port=5001)

**Comment by prithi** [comment]
Use port 3000

**Comment by jakebian** [comment]
@isaacgerg are you getting a 404 on localhost:3000? Npm run launches the app at a different port (defaults to 3000, can set via another environment variable).

If you want to get it to run on your 5001 port you need to run `npm run deploy:prod`

**Comment by isaacgerg** [comment]
@jakebian localhost:3000 gives me 3 dots, 2 which spin around a center one.

Right now, I dont care what port I run at, I just want to help get it working. I've never worked with node.js before so Im a complete noob.

**Comment by isaacgerg** [comment]
@prithi where do i put port 3000? the set command or in my python code or both?

**Comment by isaacgerg** [comment]
@jakebian Got it sort of working.  Did the `npm run deploy:prod` and then ran my python code (same as above).

I can see my images on the right but there is no graph of my model on the left.  What can I do to try to and figure this out?

**Comment by prithi** [comment]
@isaacgerg Now change this [line of code](https://github.com/jakebian/quiver/blob/master/quiver_engine/server.py#L27)

`single_input_shape = model.get_input_shape_at(0)[2:4]`

**Comment by isaacgerg** [comment]
@prithi That fix didnt change anything.  My images are not RGB.

**Comment by isaacgerg** [comment]
Nothing in server.py under get_* is being called. From following the code, I think its because there is not model shown on the left of the browser.  How do you parse apart the model?  Can it handle model's in models?

**Comment by isaacgerg** [comment]
`model.to_json()
'{"class_name": "Model", "config": {"input_layers": [["input_1", 0, 0]], "name": "model_3", "layers": [{"inbound_nodes": [], "name": "input_1", "config": {"batch_input_shape": [null, 1, 400, 400], "input_dtype": "float32", "name": "input_1"}, "class_name": "InputLayer"}, {"inbound_nodes": [[["input_1", 0, 0]]], "name": "averagepooling2d_2", "config": {"strides": [4, 4], "border_mode": "valid", "trainable": true, "name": "averagepooling2d_2", "dim_ordering": "th", "pool_size": [4, 4]}, "class_name": "AveragePooling2D"}, {"inbound_nodes": [[["input_1", 0, 0]]], "name": "averagepooling2d_1", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "averagepooling2d_1", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "AveragePooling2D"}, {"inbound_nodes": [[["averagepooling2d_2", 0, 0]]], "name": "gaussiannoise_2", "config": {"trainable": true, "name": "gaussiannoise_2", "sigma": 0.1}, "class_name": "GaussianNoise"}, {"inbound_nodes": [[["averagepooling2d_1", 0, 0]]], "name": "gaussiannoise_1", "config": {"trainable": true, "name": "gaussiannoise_1", "sigma": 0.1}, "class_name": "GaussianNoise"}, {"inbound_nodes": [[["gaussiannoise_2", 0, 0]]], "name": "flatten_2", "config": {"trainable": true, "name": "flatten_2"}, "class_name": "Flatten"}, {"inbound_nodes": [[["gaussiannoise_1", 0, 0]]], "name": "flatten_1", "config": {"trainable": true, "name": "flatten_1"}, "class_name": "Flatten"}, {"inbound_nodes": [[["flatten_2", 0, 0]]], "name": "repeatvector_2", "config": {"trainable": true, "name": "repeatvector_2", "n": 3}, "class_name": "RepeatVector"}, {"inbound_nodes": [[["flatten_1", 0, 0]]], "name": "repeatvector_1", "config": {"trainable": true, "name": "repeatvector_1", "n": 3}, "class_name": "RepeatVector"}, {"inbound_nodes": [[["repeatvector_2", 0, 0]]], "name": "reshape_2", "config": {"trainable": true, "name": "reshape_2", "target_shape": [3, 100, 100]}, "class_name": "Reshape"}, {"inbound_nodes": [[["repeatvector_1", 0, 0]]], "name": "reshape_1", "config": {"trainable": true, "name": "reshape_1", "target_shape": [3, 200, 200]}, "class_name": "Reshape"}, {"inbound_nodes": [[["reshape_2", 0, 0]]], "name": "model_2", "config": {"input_layers": [["input_3", 0, 0]], "name": "model_2", "layers": [{"inbound_nodes": [], "name": "input_3", "config": {"batch_input_shape": [null, 3, null, null], "input_dtype": "float32", "name": "input_3"}, "class_name": "InputLayer"}, {"inbound_nodes": [[["input_3", 0, 0]]], "name": "block1_conv1_2", "config": {"nb_filter": 64, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block1_conv1_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block1_conv1_2", 0, 0]]], "name": "block1_conv2_2", "config": {"nb_filter": 64, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block1_conv2_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block1_conv2_2", 0, 0]]], "name": "block1_pool_2", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block1_pool_2", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block1_pool_2", 0, 0]]], "name": "block2_conv1_2", "config": {"nb_filter": 128, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block2_conv1_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block2_conv1_2", 0, 0]]], "name": "block2_conv2_2", "config": {"nb_filter": 128, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block2_conv2_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block2_conv2_2", 0, 0]]], "name": "block2_pool_2", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block2_pool_2", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block2_pool_2", 0, 0]]], "name": "block3_conv1_2", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv1_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv1_2", 0, 0]]], "name": "block3_conv2_2", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv2_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv2_2", 0, 0]]], "name": "block3_conv3_2", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv3_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv3_2", 0, 0]]], "name": "block3_pool_2", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block3_pool_2", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block3_pool_2", 0, 0]]], "name": "block4_conv1_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv1_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv1_2", 0, 0]]], "name": "block4_conv2_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv2_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv2_2", 0, 0]]], "name": "block4_conv3_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv3_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv3_2", 0, 0]]], "name": "block4_pool_2", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block4_pool_2", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block4_pool_2", 0, 0]]], "name": "block5_conv1_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv1_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv1_2", 0, 0]]], "name": "leakyrelu_4", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_4"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_4", 0, 0]]], "name": "block5_conv2_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv2_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv2_2", 0, 0]]], "name": "leakyrelu_5", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_5"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_5", 0, 0]]], "name": "block5_conv3_2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv3_2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv3_2", 0, 0]]], "name": "leakyrelu_6", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_6"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_6", 0, 0]]], "name": "block5_pool_2", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block5_pool_2", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}], "output_layers": [["block5_pool_2", 0, 0]]}, "class_name": "Model"}, {"inbound_nodes": [[["reshape_1", 0, 0]]], "name": "model_1", "config": {"input_layers": [["input_2", 0, 0]], "name": "model_1", "layers": [{"inbound_nodes": [], "name": "input_2", "config": {"batch_input_shape": [null, 3, null, null], "input_dtype": "float32", "name": "input_2"}, "class_name": "InputLayer"}, {"inbound_nodes": [[["input_2", 0, 0]]], "name": "block1_conv1", "config": {"nb_filter": 64, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block1_conv1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block1_conv1", 0, 0]]], "name": "block1_conv2", "config": {"nb_filter": 64, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block1_conv2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block1_conv2", 0, 0]]], "name": "block1_pool", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block1_pool", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block1_pool", 0, 0]]], "name": "block2_conv1", "config": {"nb_filter": 128, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block2_conv1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block2_conv1", 0, 0]]], "name": "block2_conv2", "config": {"nb_filter": 128, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block2_conv2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block2_conv2", 0, 0]]], "name": "block2_pool", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block2_pool", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block2_pool", 0, 0]]], "name": "block3_conv1", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv1", 0, 0]]], "name": "block3_conv2", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv2", 0, 0]]], "name": "block3_conv3", "config": {"nb_filter": 256, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block3_conv3", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block3_conv3", 0, 0]]], "name": "block3_pool", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block3_pool", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block3_pool", 0, 0]]], "name": "block4_conv1", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv1", 0, 0]]], "name": "block4_conv2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv2", 0, 0]]], "name": "block4_conv3", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": false, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "relu", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block4_conv3", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block4_conv3", 0, 0]]], "name": "block4_pool", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block4_pool", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}, {"inbound_nodes": [[["block4_pool", 0, 0]]], "name": "block5_conv1", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv1", 0, 0]]], "name": "leakyrelu_1", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_1"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_1", 0, 0]]], "name": "block5_conv2", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv2", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv2", 0, 0]]], "name": "leakyrelu_2", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_2"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_2", 0, 0]]], "name": "block5_conv3", "config": {"nb_filter": 512, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "block5_conv3", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["block5_conv3", 0, 0]]], "name": "leakyrelu_3", "config": {"alpha": 0.01, "trainable": true, "name": "leakyrelu_3"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_3", 0, 0]]], "name": "block5_pool", "config": {"strides": [2, 2], "border_mode": "valid", "trainable": true, "name": "block5_pool", "dim_ordering": "th", "pool_size": [2, 2]}, "class_name": "MaxPooling2D"}], "output_layers": [["block5_pool", 0, 0]]}, "class_name": "Model"}, {"inbound_nodes": [[["model_2", 1, 0]]], "name": "upsampling2d_1", "config": {"trainable": true, "name": "upsampling2d_1", "size": [2, 2]}, "class_name": "UpSampling2D"}, {"inbound_nodes": [[["model_1", 1, 0], ["upsampling2d_1", 0, 0]]], "name": "merge_1", "config": {"mode": "sum", "output_shape_type": "raw", "dot_axes": -1, "output_shape": null, "mode_type": "raw", "name": "merge_1", "concat_axis": -1}, "class_name": "Merge"}, {"inbound_nodes": [[["merge_1", 0, 0]]], "name": "convolution2d_1", "config": {"nb_filter": 64, "activity_regularizer": null, "b_regularizer": null, "border_mode": "same", "trainable": true, "W_constraint": null, "init": "glorot_uniform", "dim_ordering": "th", "activation": "linear", "nb_col": 3, "W_regularizer": null, "b_constraint": null, "bias": true, "name": "convolution2d_1", "subsample": [1, 1], "nb_row": 3}, "class_name": "Convolution2D"}, {"inbound_nodes": [[["convolution2d_1", 0, 0]]], "name": "leakyrelu_7", "config": {"trainable": true, "alpha": 0.01, "name": "leakyrelu_7"}, "class_name": "LeakyReLU"}, {"inbound_nodes": [[["leakyrelu_7", 0, 0]]], "name": "spatialdropout2d_1", "config": {"trainable": true, "name": "spatialdropout2d_1", "p": 0.5}, "class_name": "SpatialDropout2D"}, {"inbound_nodes": [[["spatialdropout2d_1", 0, 0]]], "name": "flatten_3", "config": {"trainable": true, "name": "flatten_3"}, "class_name": "Flatten"}, {"inbound_nodes": [[["flatten_3", 0, 0]]], "name": "maxoutdense_1", "config": {"activity_regularizer": null, "nb_feature": 4, "output_dim": 8, "trainable": true, "input_dim": null, "W_constraint": null, "init": "glorot_uniform", "W_regularizer": null, "b_regularizer": null, "b_constraint": null, "bias": true, "name": "maxoutdense_1"}, "class_name": "MaxoutDense"}, {"inbound_nodes": [[["maxoutdense_1", 0, 0]]], "name": "dropout_1", "config": {"trainable": true, "name": "dropout_1", "p": 0.5}, "class_name": "Dropout"}, {"inbound_nodes": [[["dropout_1", 0, 0]]], "name": "maxoutdense_2", "config": {"activity_regularizer": null, "nb_feature": 4, "output_dim": 4, "trainable": true, "input_dim": null, "W_constraint": null, "init": "glorot_uniform", "W_regularizer": null, "b_regularizer": null, "b_constraint": null, "bias": true, "name": "maxoutdense_2"}, "class_name": "MaxoutDense"}, {"inbound_nodes": [[["maxoutdense_2", 0, 0]]], "name": "dropout_2", "config": {"trainable": true, "name": "dropout_2", "p": 0.5}, "class_name": "Dropout"}, {"inbound_nodes": [[["dropout_2", 0, 0]]], "name": "dense_1", "config": {"activity_regularizer": null, "b_regularizer": null, "output_dim": 2, "trainable": true, "input_dim": null, "W_constraint": null, "init": "glorot_uniform", "activation": "softmax", "W_regularizer": null, "b_constraint": null, "bias": true, "name": "dense_1"}, "class_name": "Dense"}], "output_layers": [["dense_1", 0, 0]]}, "keras_version": "1.0.8"}'
`

**Comment by prithi** [comment]
@isaacgerg can you show the error log you get?

**Comment by isaacgerg** [comment]
@prithi I don't get an error log that I can see.  Where should I look?

**Comment by prithi** [comment]
@isaacgerg Can you run this code and see if the model loads in the left side?

```python
from quiver_engine import server
from keras.applications.resnet50 import ResNet50

model = ResNet50(weights='imagenet')
server.launch(
        model, # a Keras Model

        # where to store temporary files generatedby quiver (e.g. image files of layers)
        temp_folder='./tmp',

        # a folder where input images are stored
        input_folder='./img',

        # the localhost port the dashboard is to be served on
        port=3000
    )
```

**Comment by jakebian** [comment]
Hey guys this is getting off-topic from the original issue. I made a [gitter](https://gitter.im/quiverEngine), as TF dependency is now optional can we close this issue and move the discussion there?

**Comment by isaacgerg** [comment]
@prithi Yes!  That model works and I see it on the left.  I have filed a separate issue as it seems quiver_server cannot handle complex models.

**Comment by vfdev-5** [comment]
Hi guys, 
I do not catch, anyway, how TF dependency is now optional whenever under Windows `pip install quiver_engine` requires it and [setup.py](https://github.com/jakebian/quiver/blob/master/setup.py) specifies it in `install_requires` ?
Can somebody tell me, how to install `quiver` without TF (and with Theano) on Windows ?
Thanks,
Cheers
