### ISSUE TITLE
number of channels only 3?

### ISSUE THREAD

**Issue by varoudis** [jakebian/quiver#14]
What happens if the model is for one channel images?

Exception: Error when checking : expected input_1 to have shape (1, 128, 128, 1) but got array with shape (1, 128, 128, 3)

**Comment by zulmaster** [comment]
Please add support

**Comment by varoudis** [comment]
hmm I hacked the util.py and I forced greyscale=True on image.load but I still get the "Exception: Error when checking : expected input_1 to have shape (1, 128, 128, 1) but got array with shape (1, 128, 128, 3)"

**Comment by jakebian** [comment]
Looks like you disagree with keras on the [spelling of 'gray'](https://github.com/fchollet/keras/blob/80fbbc3a6a2a30f391bad2aa85e7558c50ca0709/keras/preprocessing/image.py#L163). `grayscale` with an `a`.

**Comment by varoudis** [comment]
Hehe no my spelling here is wrong, it wasnt copy/paste from the code.

Do yu have any plans to make it work with one channel images?

**Comment by jakebian** [comment]
Yes definitely something I'm planning to support, but need to spend some time to figure it out. If you figure it out in the meantime feel free to send a PR!

**Comment by dan-1d** [comment]
I just submitted a pull request that should fix this.

**Comment by jakebian** [comment]
merged https://github.com/jakebian/quiver/pull/25, @varoudis can you verify that this is solved?

**Comment by varoudis** [comment]
@jakebian it seems to be doing something. loading seems ok.

Do we need something equivalent for one channel in 'preprocess_input'?

**Comment by varoudis** [comment]
error when changing test images. you do get an result though.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/server.py", line 133, in get_prediction
    model.predict(input_img)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/imagenet_utils.py", line 42, in decode_predictions
    'Found array with shape: ' + str(preds.shape))
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 128, 128, 1)
10.200.200.14 - - [2016-11-21 10:09:17] "GET /predict/sub_100_00000186.png HTTP/1.1" 500 412 0.038075
10.200.200.14 - - [2016-11-21 10:09:17] "GET /layer/convolution2d_21/sub_100_00000186.png HTTP/1.1" 200 168 0.810472
10.200.200.14 - - [2016-11-21 10:09:17] "GET /temp-file/convolution2d_21_0_sub_100_00000186.png.png HTTP/1.1" 200 2666 0.001973
```

**Comment by jakebian** [comment]
Ah prediction endpoint is expected to fail for non-imagenet things for now, there's a pr to fix that I'll merge today
