### ISSUE TITLE
Proper path use in get_output_name()

### ISSUE THREAD

**Issue by isaacgerg** [jakebian/quiver#19]
quiver_engine/server.py get_output_name() should use os.sep instead of '/'.  

Original convention breaks PIL im.save(). E.g. im.save(r'e:\tmp/filename.png') will result in OSError, Invalid Argument.

Furthermore, ensure all paths should use os.path.join or os.sep instead of '/'.

**Comment by jakebian** [comment]
Isn't this a duplicated of https://github.com/jakebian/quiver/issues/9?

**Comment by isaacgerg** [comment]
no.  Take a look at quiver_engine/server.py get_output_name(), you have a hardcoded '\'.  

The issue with #9 is that input_path isn't propagated in the system.

**Comment by isaacgerg** [comment]
This appears to be fixed.  Closing.
