### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by guozhizou** [jakebian/quiver#24]
Followed the Development guide, got this issue. I tried to change react and react-dom in package.json to 0.14.8, but got other conflicts.
 
```
quiverboard git:(master) npm install
npm WARN halogen@0.2.0 requires a peer of react@^0.14.8 but none was installed.
npm WARN halogen@0.2.0 requires a peer of react-dom@^0.14.8 but none was installed.
```

**Comment by jakebian** [comment]
These are warnings, not errors, should not actually affect the success of the installation.
