### ISSUE TITLE
get_shape undefined with keras 1.1.0

### ISSUE THREAD

**Issue by unrealwill** [jakebian/quiver#3]
With keras version '1.1.0', it was not knowing the get_shape in server.py line 25
I had to clone the repository and 
modify it to single_input_shape = model.get_input_shape_at(0)[1:3]

I also add (not specified in your quickstart) to install better-npm-run and do a npm install.

It seems to resolve this error but I then bump into an other issue ( idle 127.0.0.1 - - [2016-11-14 18:37:18] "GET / HTTP/1.1" 404 374 0.000843 )  which you are already working on.

**Comment by jakebian** [comment]
Good catch, looks like `get_input_shape_at` is compatible with older versions too so yes we should use that instead. Feel free to send your branch with that as a PR! The 404 issue should be fixed now.

**Comment by jakebian** [comment]
Made the change in https://github.com/jakebian/quiver/commit/fa0ee734dc9af41d699eddbc07b6aa3d12f8ee46
