### ISSUE TITLE
No module named 'imagenet_utils'

### ISSUE THREAD

**Issue by kmader** [jakebian/quiver#4]
```ImportError: No module named 'imagenet_utils'``` which seems to be coming from this line

https://github.com/jakebian/quiver/blob/master/quiver_engine/util.py#L4
which refers to this library
https://github.com/fchollet/deep-learning-models/blob/master/imagenet_utils.py

It seems like this dependency is anyways only valid if the training set is imagenet based so maybe it would be good to make this more flexible and explicitly include the deep-learning-models as a dependency?

**Comment by jakebian** [comment]
Odd. An imagenet_utils file is included here https://github.com/jakebian/quiver/blob/master/quiver_engine/imagenet_utils.py. Could be a Python imports issue - are you on python 3?

Removing imagenet-specific code is something we definitely should do, agreed.

**Comment by kmader** [comment]
ah, yea I just saw that, I am on python 3 and so there are a lot of references that don't work, I'll fork it and use the ```from ___future__ import absolute_import``` to keep everything consistent

**Comment by jakebian** [comment]
Great - feel free to send a PR once you've done that!

**Comment by carlthome** [comment]
Yikes, no Python 3 support? I ran into the same issue.

**Comment by kretes** [comment]
I guess this https://github.com/jakebian/quiver/pull/5 solve this problem?

**Comment by LGestin** [comment]
I made some modifications that fixed this for me.
In the file server.py, change the line 20: 'imagenet_utils import decode_prediction' with 'from quiver_engine.imagenet_utils import decode_prediction'
Same trick has to be applied to the two following lines (lines 21 & 22) and in line 4 of util.py file.
After that, no more ImportError.

**Comment by jakebian** [comment]
https://github.com/jakebian/quiver/pull/5 merged!
