### ISSUE TITLE
Input shape and channels should be set based on image_dim_ordering

### ISSUE THREAD

**Issue by bafu** [jakebian/quiver#43]
In [Keras backends document](https://keras.io/backend/), `image_dim_ordering` controls how to interpret the information of image shape and input channel.

In current source code, `keras.backend.backend()` is used as the condition instead of `keras.backend.image_dim_ordering()`. TensorFlow backend is possible to use `th` as its dimension ordering convention, and vice versa.

**Comment by jakebian** [comment]
Merged your PR, good catch!
